apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: devopswithai-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway # Uses the default istio ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "devopswithai.in"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE # Assumes cert is managed by Istio/Cert-Manager
      credentialName: devopswithai-cert-secret
    hosts:
    - "devopswithai.in"
