apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devopswithai-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: "devopswithai-cert"
    kubernetes.io/ingress.global-static-ip-name: "devopswithai-ip" # Optional: if you reserve a static IP
    networking.gke.io/v1beta1.FrontendConfig: "devopswithai-frontend-config"
spec:
  defaultBackend:
    service:
      name: devopswithai-service
      port:
        number: 80
  rules:
  - host: devopswithai.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devopswithai-service
            port:
              number: 80
  - host: www.devopswithai.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devopswithai-service
            port:
              number: 80
