apiVersion: v1
kind: Service
metadata:
  name: search-api-service
  labels:
    app: search-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: search-api
